config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :incomes
  resources :expenses
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  validates :category, presence: true
  validates :amount, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :date, presence: true
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  validates :category, presence: true
  validates :amount, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :expenses, dependent: :nullify
  has_many :incomes, dependent: :nullify

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [ :edit, :update, :destroy ]

  def new
    @expense = Expense.new()
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    if @expense.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @expense.update(expense_params)
    if @expense.save
      redirect_to user_path(current_user)
    else
      render :update
    end
  end

  def destroy
    @expense.delete
    redirect_to user_path(current_user)
  end

  private
  def expense_params
    params.require(:expense).permit(:expense_type, :category, :amount, :comment, :date)
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:edit, :update, :destroy]

  def new
    @income = Income.new()
  end

  def create
    @income = Income.new(income_params)
    @income.user = current_user
    if @income.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @income.update(income_params)
    if @income.save
      redirect_to user_path(current_user)
    else
      render :update
    end
  end

  def destroy
    @income.delete
    redirect_to user_path(current_user)
  end

  private
  def income_params
    params.require(:income).permit(:category, :amount, :comment, :date)
  end

  def set_income
    @income = Income.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @incomes = current_user.incomes
    @expenses = current_user.expenses
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="form-container">
          <h4>Update your <%= @expense.category %> expense</h4>
          <%= simple_form_for @expense do |f| %>
            <div class="category expense-category text-center col-xs-4" id="Transports">
              <div class="category-content">
                <i class="fa fa-subway" aria-hidden="true"></i>
                <p>Transports</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Phone">
              <div class="category-content">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <p>Phone</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4"  id="Subscriptions">
              <div class="category-content">
                <i class="fa fa-ticket" aria-hidden="true"></i>
                <p>Subscriptions</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Savings">
              <div class="category-content">
                <i class="fa fa-money" aria-hidden="true"></i>
                <p>Savings</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Income taxes">
              <div class="category-content">
                <i class="fa fa-euro" aria-hidden="true"></i>
                <p>Income taxes</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Rent">
              <div class="category-content">
                <i class="fa fa-home" aria-hidden="true"></i>
                <p>Rent</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Insurance">
              <div class="category-content">
                <i class="fa fa-euro" aria-hidden="true"></i>
                <p>Insurance</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Home taxes">
              <div class="category-content">
                <i class="fa fa-euro" aria-hidden="true"></i>
                <p>Home taxes</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Lessons">
              <div class="category-content">
                <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                <p>Lessons</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Restaurants & Drinks">
              <div class="category-content">
                <i class="fa fa-cutlery" aria-hidden="true"></i>
                <p>Restaurants & Drinks</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Groceries">
              <div class="category-content">
                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                <p>Groceries</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Shopping & Holidays">
              <div class="category-content">
                <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                <p>Shopping & Holidays</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Withdrawals">
              <div class="category-content">
                <i class="fa fa-credit-card" aria-hidden="true"></i>
                <p>Withdrawals</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Health">
              <div class="category-content">
                <i class="fa fa-medkit" aria-hidden="true"></i>
                <p>Health</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Gifts">
              <div class="category-content">
                <i class="fa fa-gift" aria-hidden="true"></i>
                <p>Gifts</p>
              </div>
            </div>
            <%= f.input :category, collection: [ "Transports", "Subscriptions", "Phone", "Savings", "Income taxes", "Home taxes", "Rent", "Insurance", "Courses", "Restaurants & Drinks", "Groceries", "Shopping & Holidays", "Health", "Withdrawals", "Gifts" ], as: :hidden %>
            <%= f.input :amount %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%= f.input :comment %>
            <%= f.submit class: "btn btn-primary btn-lg"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="form-container">
          <h4>Add a new expense</h4>
          <%= simple_form_for @expense do |f| %>
            <div class="category expense-category text-center col-xs-4" id="Transports">
              <div class="category-content">
                <i class="fa fa-subway" aria-hidden="true"></i>
                <p>Transports</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Phone">
              <div class="category-content">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <p>Phone</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4"  id="Subscriptions">
              <div class="category-content">
                <i class="fa fa-ticket" aria-hidden="true"></i>
                <p>Subscriptions</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Savings">
              <div class="category-content">
                <i class="fa fa-money" aria-hidden="true"></i>
                <p>Savings</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Income taxes">
              <div class="category-content">
                <i class="fa fa-euro" aria-hidden="true"></i>
                <p>Income taxes</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Rent">
              <div class="category-content">
                <i class="fa fa-home" aria-hidden="true"></i>
                <p>Rent</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Insurance">
              <div class="category-content">
                <i class="fa fa-euro" aria-hidden="true"></i>
                <p>Insurance</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Home taxes">
              <div class="category-content">
                <i class="fa fa-euro" aria-hidden="true"></i>
                <p>Home taxes</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Lessons">
              <div class="category-content">
                <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                <p>Lessons</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Restaurants & Drinks">
              <div class="category-content">
                <i class="fa fa-cutlery" aria-hidden="true"></i>
                <p>Restaurants & Drinks</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Groceries">
              <div class="category-content">
                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                <p>Groceries</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Shopping & Holidays">
              <div class="category-content">
                <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                <p>Shopping & Holidays</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Withdrawals">
              <div class="category-content">
                <i class="fa fa-credit-card" aria-hidden="true"></i>
                <p>Withdrawals</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Health">
              <div class="category-content">
                <i class="fa fa-medkit" aria-hidden="true"></i>
                <p>Health</p>
              </div>
            </div>
            <div class="category expense-category text-center col-xs-4" id="Gifts">
              <div class="category-content">
                <i class="fa fa-gift" aria-hidden="true"></i>
                <p>Gifts</p>
              </div>
            </div>
            <%= f.input :category, collection: [ "Transports", "Subscriptions", "Phone", "Savings", "Income taxes", "Home taxes", "Rent", "Insurance", "Courses", "Restaurants & Drinks", "Groceries", "Shopping & Holidays", "Health", "Withdrawals", "Gifts" ], as: :hidden %>
            <%= f.input :amount %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%= f.input :comment %>
            <%= f.submit class: "btn btn-primary btn-lg"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/incomes/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="form-container">
          <h4>Update your <%= @income.category %> income</h4>
          <%= simple_form_for @income do |f| %>
            <div class="category income-category text-center col-xs-4" id="Salary">
              <div class="category-content">
                <i class="fa fa-briefcase" aria-hidden="true"></i>
                <p>Salary</p>
              </div>
            </div>
            <div class="category income-category text-center col-xs-4" id="From savings">
              <div class="category-content">
                <i class="fa fa-money" aria-hidden="true"></i>
                <p>From savings</p>
              </div>
            </div>
            <div class="category income-category text-center col-xs-4" id="Others">
              <div class="category-content">
                <i class="fa fa-gift" aria-hidden="true"></i>
                <p>Others</p>
              </div>
            </div>
            <%= f.input :category, collection: [ "Salary", "Transfer from savings", "Others" ], as: :hidden %>
            <%= f.input :amount %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%= f.input :comment %>
            <%= f.submit class: "btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/incomes/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="form-container">
          <h4>Add a new income</h4>
          <%= simple_form_for @income do |f| %>
            <div class="category income-category text-center col-xs-4" id="Salary">
              <div class="category-content">
                <i class="fa fa-briefcase" aria-hidden="true"></i>
                <p>Salary</p>
              </div>
            </div>
            <div class="category income-category text-center col-xs-4" id="From savings">
              <div class="category-content">
                <i class="fa fa-money" aria-hidden="true"></i>
                <p>From savings</p>
              </div>
            </div>
            <div class="category income-category text-center col-xs-4" id="Others">
              <div class="category-content">
                <i class="fa fa-gift" aria-hidden="true"></i>
                <p>Others</p>
              </div>
            </div>
            <%= f.input :category, collection: [ "Salary", "Transfer from savings", "Others" ], as: :hidden %>
            <%= f.input :amount %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%= f.input :comment %>
            <%= f.submit class: "btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget dashboard</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'dollar.png' %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
    </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Welcome to your budget manager</h1>
    <%= link_to "Add a new income", new_income_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Add a new expense", new_expense_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "dollar.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= link_to '#', class: "dropdown-toggle navbar-wagon-link", id: "navbar-wagon-menu", "data-toggle" => "dropdown" do %>
            <%= current_user.email %>
            <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="operations">
      <h4>Incomes</h4>
      <table>
        <tr>
          <th>Date</th>
          <th>Amount</th>
          <th>Category</th>
          <th>Comment</th>
        </tr>
        <% @incomes.each do |income| %>
          <tr>
            <td><%= income.date.strftime('%d/%m/%Y') %></td>
            <td><%= income.amount %></td>
            <td><%= income.category %></td>
            <td><%= income.comment ? income.comment : "" %></td>
            <td class="no-line">
              <%= link_to "", edit_income_path(income), class: "fa fa-pencil" %>
              <%= link_to "", income_path(income), method: :delete, data: { confirm: "Are you sure?"}, class: "fa fa-trash" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="container">
    <div class="operations">
      <h4>Expenses</h4>
      <table>
        <tr>
          <th>Date</th>
          <th>Amount</th>
          <th>Category</th>
          <th>Comment</th>
        </tr>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= expense.date.strftime('%d/%m/%Y') %></td>
            <td><%= expense.amount %></td>
            <td><%= expense.category %></td>
            <td><%= expense.comment ? expense.comment : "" %></td>
            <td class="no-line">
              <%= link_to "", edit_expense_path(expense), class: "fa fa-pencil" %>
              <%= link_to "", expense_path(expense), method: :delete, data: { confirm: "Are you sure?"}, class: "fa fa-trash" %></td>
        </tr>
        <% end %>
      </table>
      <%#= pie_chart @expenses.group(:category).count %>
    </div>
  </div>
</div>